apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: redis-spinapp
spec:
  image: "ghcr.io/spinkube/redis-sample:20240805-185905-gdb3271f"
  replicas: 1
  executor: containerd-shim-spin
# Steps to run this found at https://github.com/spinkube/spin-operator/pull/131